version: '3.8'
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    networks:
      default-network:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      default-network:

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1880:1880"
    networks:
      default-network:
    volumes:
      - node-red-data:/data

volumes:
  prom_data:
  grafana-storage:
  node-red-data:
networks:
  default-network:
